# Generated by Django 6.0 on 2025-12-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente Confirmación'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso (Equipos entregados)'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at_pickup', models.DateTimeField(blank=True, null=True)),
                ('scanned_at_return', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
