
FROM node:18-alpine

RUN npm install -g pnpm @angular/cli

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile


EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
