# Generated by Django 6.0 on 2025-12-13 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_paquetes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paqueteitem',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.equipo'),
        ),
        migrations.AddField(
            model_name='paqueteitem',
            name='paquete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.paquete'),
        ),
    ]
