# Generated by Django 6.0 on 2025-12-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.package'),
        ),
        migrations.AddField(
            model_name='publication',
            name='catalog_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.catalogproduct'),
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packageitem',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.publication'),
        ),
        migrations.AddField(
            model_name='unit',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.publication'),
        ),
        migrations.AddField(
            model_name='calendarblock',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='inventory.unit'),
        ),
    ]
