# Generated by Django 5.2.7 on 2025-12-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='product_type',
            field=models.CharField(blank=True, help_text='Ej: Subwoofer Activo, Máquina de Humo, Pantalla LED', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogproduct',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
